
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tml-demo2
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jar
  template:
    metadata:
      labels:
        app: jar
    spec:
      containers:
        - name: tmldevops
          image: 653709203391.dkr.ecr.us-east-1.amazonaws.com/jenkinspipleine:98
          imagePullPolicy: Always
          ports:
          -  containerPort: 8080
          
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: tml-demo2
spec:
  selector:
    app: tml-demo2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
          
        



       
